<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LgWysLQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LgWysLQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LgWysLQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'apuser' => ['privates', '.errored..service_locator.LgWysLQ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.LgWysLQ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'chantier' => ['privates', '.errored..service_locator.LgWysLQ.App\\Entity\\Chantier', NULL, 'Cannot autowire service ".service_locator.LgWysLQ": it needs an instance of "App\\Entity\\Chantier" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'master' => ['privates', '.errored..service_locator.LgWysLQ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.LgWysLQ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'apuser' => 'App\\Entity\\User',
            'chantier' => 'App\\Entity\\Chantier',
            'doctrine' => '?',
            'master' => 'App\\Entity\\User',
        ]);
    }
}
