<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tx04pqLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tx04pqL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tx04pqL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bon' => ['privates', '.errored..service_locator.tx04pqL.App\\Entity\\Bon', NULL, 'Cannot autowire service ".service_locator.tx04pqL": it needs an instance of "App\\Entity\\Bon" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'bon' => 'App\\Entity\\Bon',
            'doctrine' => '?',
        ]);
    }
}
