<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BP34QwfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bP34Qwf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bP34Qwf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'master' => ['privates', '.errored..service_locator.bP34Qwf.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.bP34Qwf": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'section' => ['privates', '.errored..service_locator.bP34Qwf.App\\Entity\\Section', NULL, 'Cannot autowire service ".service_locator.bP34Qwf": it needs an instance of "App\\Entity\\Section" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'master' => 'App\\Entity\\User',
            'section' => 'App\\Entity\\Section',
        ]);
    }
}
