<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IAU9lZfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IAU9lZf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IAU9lZf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'facture' => ['privates', '.errored..service_locator.IAU9lZf.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.IAU9lZf": it needs an instance of "App\\Entity\\Facture" but this type has been excluded in "config/services.yaml".'],
        ], [
            'facture' => 'App\\Entity\\Facture',
        ]);
    }
}
