<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLigneCommandeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiLigneCommandeController' shared autowired service.
     *
     * @return \App\Controller\ApiLigneCommandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ApiLigneCommandeController.php';

        $container->services['App\\Controller\\ApiLigneCommandeController'] = $instance = new \App\Controller\ApiLigneCommandeController(($container->services['doctrine'] ?? self::getDoctrineService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ApiLigneCommandeController', $container));

        return $instance;
    }
}
