<?php

namespace ContainerM5Xx18V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XYKQUiM.App\Entity\Planning' shared service.
     *
     * @return \App\Entity\Planning
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XYKQUiM": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".');
    }
}
