<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VXAyESVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vXAyESV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vXAyESV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'planning' => ['privates', '.errored..service_locator.vXAyESV.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.vXAyESV": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'planning' => 'App\\Entity\\Planning',
        ]);
    }
}
