<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BaeB_CAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BaeB.cA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'uploaders' => ['privates', 'App\\Service\\FileUploaders', 'getFileUploadersService', true],
        ], [
            'mailer' => '?',
            'uploaders' => 'App\\Service\\FileUploaders',
        ]);

        if (isset($container->privates['.service_locator.BaeB.cA'])) {
            return $container->privates['.service_locator.BaeB.cA'];
        }

        return $container->privates['.service_locator.BaeB.cA'] = $instance;
    }
}
