<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCv23U5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DCv23U5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DCv23U5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chantier' => ['privates', '.errored..service_locator.DCv23U5.App\\Entity\\Chantier', NULL, 'Cannot autowire service ".service_locator.DCv23U5": it needs an instance of "App\\Entity\\Chantier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chantier' => 'App\\Entity\\Chantier',
        ]);
    }
}
