<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OxX4FphService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OxX4Fph' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OxX4Fph'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'devis' => ['privates', '.errored..service_locator.OxX4Fph.App\\Entity\\Devis', NULL, 'Cannot autowire service ".service_locator.OxX4Fph": it needs an instance of "App\\Entity\\Devis" but this type has been excluded in "config/services.yaml".'],
        ], [
            'devis' => 'App\\Entity\\Devis',
        ]);
    }
}
