<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PHl1xFmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PHl1xFm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PHl1xFm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bon' => ['privates', '.errored..service_locator.PHl1xFm.App\\Entity\\Bon', NULL, 'Cannot autowire service ".service_locator.PHl1xFm": it needs an instance of "App\\Entity\\Bon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bon' => 'App\\Entity\\Bon',
        ]);
    }
}
