<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YkQ6XnQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YkQ6XnQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YkQ6XnQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'uploaders' => ['privates', 'App\\Service\\FileUploaders', 'getFileUploadersService', true],
        ], [
            'uploaders' => 'App\\Service\\FileUploaders',
        ]);
    }
}
