<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChantier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LgWysLQ.App\Entity\Chantier' shared service.
     *
     * @return \App\Entity\Chantier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LgWysLQ": it needs an instance of "App\\Entity\\Chantier" but this type has been excluded in "config/services.yaml".');
    }
}
