<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OxX4Fph.App\Entity\Devis' shared service.
     *
     * @return \App\Entity\Devis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OxX4Fph": it needs an instance of "App\\Entity\\Devis" but this type has been excluded in "config/services.yaml".');
    }
}
