<?php

namespace ContainerEAhoiP9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosCkEditor_ConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_ck_editor.configuration' shared autowired service.
     *
     * @return \FOS\CKEditorBundle\Config\CKEditorConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'friendsofsymfony'.\DIRECTORY_SEPARATOR.'ckeditor-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Config'.\DIRECTORY_SEPARATOR.'CKEditorConfigurationInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'friendsofsymfony'.\DIRECTORY_SEPARATOR.'ckeditor-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Config'.\DIRECTORY_SEPARATOR.'CKEditorConfiguration.php';

        return $container->services['fos_ck_editor.configuration'] = new \FOS\CKEditorBundle\Config\CKEditorConfiguration(['base_path' => '/bundles/fosckeditor/', 'js_path' => '/bundles/fosckeditor/ckeditor.js', 'configs' => ['my_config_1' => ['toolbar' => 'my_toolbar_1', 'uiColor' => '#F5F5F5', 'removePlugins' => 'exportpdf'], 'my_config_2' => ['toolbar' => 'my_toolbar_2', 'uiColor' => '#F5F5F5', 'removePlugins' => 'exportpdf']], 'toolbars' => ['configs' => ['my_toolbar_1' => [['Bold', '-', 'Italic', '-', 'Underline', '-', 'Strike', '-', 'Subscript', '-', 'Superscript', '-', 'Font', '-', 'FontSize', '-', 'TextColor', '/', 'BGColor']], 'my_toolbar_2' => [['Bold', '-', 'Italic', '-', 'Underline', '-', 'Strike', '-', 'Subscript', '-', 'Superscript', '-', 'Font', '-', 'FontSize', '-', 'TextColor', '/', 'BGColor']]], 'items' => []], 'enable' => true, 'async' => false, 'auto_inline' => true, 'inline' => false, 'autoload' => true, 'jquery' => false, 'require_js' => false, 'input_sync' => false, 'jquery_path' => 'bundles/fosckeditor/adapters/jquery.js', 'default_config' => NULL, 'plugins' => [], 'styles' => [], 'templates' => [], 'filebrowsers' => []]);
    }
}
