<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'c298f9862ca845f5455665d3c7e2f10a',
  'DATABASE_URL' => 'mysql://eitechkc_cBleu:yohann@12Y@127.0.0.1:3306/eitechkc_allblue',
  'MAILER_DSN' =>  'smtp://carlinbleu.service@gmail.com:kmowoyxnlqbrdney@smtp.gmail.com:587?encryption=tls',
  'CORS_ALLOW_ORIGIN' => '^https?://localhost(:[0-9]+)?$',
);
