<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEAhoiP9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEAhoiP9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEAhoiP9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEAhoiP9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEAhoiP9\App_KernelDevDebugContainer([
    'container.build_hash' => 'EAhoiP9',
    'container.build_id' => 'c9df10c0',
    'container.build_time' => 1776243143,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEAhoiP9');
